// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/antoinepoisson/bootstrap-go-aws/internal/awsx"
	"github.com/antoinepoisson/bootstrap-go-aws/internal/config"
	"github.com/antoinepoisson/bootstrap-go-aws/internal/item"
	"github.com/antoinepoisson/bootstrap-go-aws/lambda/public/internal/handler/health"
	"github.com/antoinepoisson/bootstrap-go-aws/lambda/public/internal/handler/items"
	"net/http"
)

// Injectors from wire.go:

func inject(cfg *config.Config) (http.Handler, error) {
	handler := health.New(cfg)
	client, err := awsx.NewDynamoDBClient(cfg)
	if err != nil {
		return nil, err
	}
	dynamoDBRepository := item.NewDynamoDBRepository(client, cfg)
	service := item.NewService(dynamoDBRepository)
	itemsHandler := items.New(service)
	httpHandler := newHandler(handler, itemsHandler)
	return httpHandler, nil
}
